---

pki_ca_workspace: "./.workspace_pki"
pki_ca:
    root_ca:
        workspace:                "{{ pki_ca_workspace }}/root_ca"
        priv_key:                 "root_ca_priv_key.pem"
        csr:                      "root.csr"
        crt:                      "root.crt"
        common_name:              "Dummy Root CA"
        country_name:             "DE"
        state_or_province_name:   "Dummyfild"
        email_address:            "ca-admin@dum.my"
        organization_name:        "Dummy GmbH"
        organizational_unit_name: "IT operation department"
        not_after:                "+1300w"
        key_usage:
            - digitalSignature
            - keyAgreement
    policy_ca:
        workspace:                "{{ pki_ca_workspace }}/policy_ca"
        ownca_path:               "{{ pki_ca_workspace }}/root_ca/root.crt"
        ownca_privatekey_path:    "{{ pki_ca_workspace }}/root_ca/root_ca_priv_key.pem"
        country_name:             "DE"
        state_or_province_name:   "Dummyfild"
        organization_name:        "Dummy GmbH"
        ca:
            staff_ca:
                name:                     "Staff CA"
                priv_key:                 "staff_ca_priv_key.pem"
                pub_key:                  "staff_ca_pub_key.pem"
                crt:                      "staff_ca.crt"
                csr:                      "staff_ca.csr"
                email_address:            "staff-ca@dum.my"
                organizational_unit_name: "Staff department"
                not_after:                "+52w"
                key_usage:
                    - digitalSignature
                    - keyAgreement
            service_ca:
                name:                     "Service CA"
                priv_key:                 "service_ca_priv_key.pem"
                pub_key:                  "service_ca_pub_key.pem"
                crt:                      "service_ca.crt"
                csr:                      "service_ca.csr"
                email_address:            "service-ca@dum.my"
                organizational_unit_name: "Service department"
                not_after:                "+26w"
                key_usage:
                    - digitalSignature
                    - keyAgreement
    staff_end_entity:
        workspace:                "{{ pki_ca_workspace }}/staff_end_entity"
        ownca_path:               "{{ pki_ca_workspace }}/root_ca/root.crt"
        ownca_privatekey_path:    "{{ pki_ca_workspace }}/root_ca/root_ca_priv_key.pem"
        not_after:                "+12w"
        country_name:             "DE"
        state_or_province_name:   "Dummyfild"
        organization_name:        "Dummy GmbH"
        staff:
            jane_doe:
                name:                     "Jane Doe"
                priv_key:                 "jane_doe_priv_key.pem"
                pub_key:                  "jane_doe_pub_key.pem"
                crt:                      "jane_doe.crt"
                csr:                      "jane_doe.csr"
                email_address:            "jane_doe@dum.my"
                organizational_unit_name: "First dummy department"
                key_usage:
                    - digitalSignature
                    - keyAgreement
                extended_key_usage:
                    - clientAuth
            john_doe:
                name:                     "John Doe"
                priv_key:                 "john_doe_priv_key.pem"
                pub_key:                  "john_doe_pub_key.pem"
                crt:                      "john_doe.crt"
                csr:                      "john_doe.csr"
                email_address:            "john_doe@dum.my"
                organizational_unit_name: "First dummy department"
                key_usage:
                    - digitalSignature
                    - keyAgreement
                extended_key_usage:
                    - clientAuth
    service_end_entity:
        workspace:                "{{ pki_ca_workspace }}/service_end_entity"
        ownca_path:               "{{ pki_ca_workspace }}/policy_ca/service_ca/service_ca.crt"
        ownca_privatekey_path:    "{{ pki_ca_workspace }}/policy_ca/service_ca/service_ca_priv_key.pem"
        not_after:                "+12w"
        country_name:             "DE"
        state_or_province_name:   "Dummyfild"
        organization_name:        "Dummy GmbH"
        service:
            app_frontend:
                name:                     "App frontend"
                priv_key:                 "app_frontend_priv_key.pem"
                pub_key:                  "app_frontend_pub_key.pem"
                crt:                      "app_frontend.crt"
                csr:                      "app_frontend.csr"
                email_address:            "service-ca@dum.my"
                organizational_unit_name: "Dummy develop department"
                key_usage:
                    - digitalSignature
                    - keyAgreement
                extended_key_usage:
                    - clientAuth
            app_backend:
                name:                     "App backend"
                priv_key:                 "app_backend_priv_key.pem"
                pub_key:                  "app_backend_pub_key.pem"
                crt:                      "app_backend.crt"
                csr:                      "app_backend.csr"
                email_address:            "service-ca@dum.my"
                organizational_unit_name: "Dummy develop department"
                key_usage:
                    - digitalSignature
                    - keyAgreement
                extended_key_usage:
                    - clientAuth