---


- name:           Get hsm objects
  shell:          |
                  yubihsm-shell                                               \
                    -a list-objects                                           \
                    -d 0                                                      \
                    -t any                                                    \
                    -A any                                                    \
                    -p {{ yubi_factory_passwd }}                              \
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

###############################################################################

- name:           Create new audit auth key
  shell:          |
                  yubihsm-shell -a put-authentication-key                     \
                    -i 0x0002                                                 \
                    -l "Audit auth key"                                       \
                    -c "all"                                                  \
                    -t "all"                                                  \
                    --delegated="all"                                         \
                    --new-password="{{ yubihsm2_password }}"                  \
                    -p "{{ yubi_factory_passwd }}"
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output


# [or@aug]$ yubihsm-shell -a put-authentication-key \
#                         -i 0x0002 \
#                         -l "Audit auth key" \
#                         -c "all" \
#                         -t "all" \
#                         --delegated="all" \
#                         --new-password="password2" \
#                         -p "password"
###############################################################################

- name:           Get hsm objects
  shell:          |
                  yubihsm-shell                                               \
                    -a list-objects                                           \
                    -d 0                                                      \
                    -t any                                                    \
                    -A any                                                    \
                    -p {{ yubi_factory_passwd }}                              \
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

###############################################################################

- name:           Delete factory key
  shell:          |
                  yubihsm-shell -a delete-object                              \
                    -i "0x0001"                                               \
                    -t "authentication-key"                                   \
                    --authkey="0x0002"                                        \
                    -p "{{ yubihsm2_password }}" 
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

# [or@aug]$ yubihsm-shell -a delete-object \
#                         -i "0x0001" \
#                         -t "authentication-key" \
#                         --authkey="0x0002"  \
#                         -p "password2" 


###############################################################################

- name:           Create test objekt with new password
  shell:          |
                  yubihsm-shell -a put-authentication-key                     \
                    -i "0x0003"                                               \
                    -c 'all'                                                  \
                    -t "all"                                                  \
                    --delegated="all"                                         \
                    -l "Test audit auth key 3"                                \
                    --new-password="{{ yubihsm2_password }}-2"                \
                    --authkey="0x0002"                                        \
                    -p "{{ yubihsm2_password }}"
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

# [or@aug]$ yubihsm-shell -a put-authentication-key 
#                         -i "0x0003" \
#                         -c 'all' \
#                         -t "all" \
#                         --delegated="all" \
#                         -l "Audit auth key 3" \
#                         --new-password="password3" \
#                         --authkey="0x0002"  \
#                         -p "password2"


# [or@aug]$ yubihsm-shell -a get-object-info \
#                         -i 0x0002 \
#                         -t authentication-key \
#                         -A any  \
#                         -p password4 \
#                         --authkey=0x9893