---

- name:           Is factory key exist
  shell:          |
                  [[                                                          \
                    $(                                                        \
                      yubihsm-shell                                           \
                      --action=list-objects                                   \
                      --domains={{ main_domain }}                             \
                      --object-type=any                                       \
                      --algorithm=any                                         \
                      --password={{ yubi_factory_key.password }}              \
                      2>&1                                                    \
                      | grep "Object not found"                               \
                      | wc -l                                                 \
                    ) == 0                                                    \
                    ]]                                                        \
                    && echo true                                              \
                    || echo false
  register:       is_factory_key_exist
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ is_factory_key_exist }}"
  when:           debug_output

###############################################################################


- name:           Create new audit auth key
  shell:          |
                  yubihsm-shell                                               \
                    --action=put-authentication-key                           \
                    --object-id={{ hsm_key.audit_auth.id }}                       \
                    --label="{{ hsm_key.audit_auth.label }}"                      \
                    --capabilities="all"                                      \
                    --object-type="all"                                       \
                    --delegated="all"                                         \
                    --new-password="{{ hsm_key.audit_auth.password }}"            \
                    --authkey="{{ yubi_factory_key.id }}"                     \
                    --password="{{ yubi_factory_key.password }}"
  register:       shell_result
  when:           is_factory_key_exist.stdout == 'true'
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

###############################################################################

- name:           Get hsm objects
  shell:          |
                  yubihsm-shell                                               \
                    --action=list-objects                                     \
                    --domains={{ main_domain }}                               \
                    --object-type=any                                         \
                    --algorithm=any                                           \
                    --authkey="{{ hsm_key.audit_auth.id }}"                       \
                    --password={{ hsm_key.audit_auth.password }}                  \
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

###############################################################################

- name:           Delete factory key
  shell:          |
                  yubihsm-shell                                               \
                    --action=delete-object                                    \
                    --object-id="{{ yubi_factory_key.id }}"                   \
                    --object-type="authentication-key"                        \
                    --authkey="{{ hsm_key.audit_auth.id }}"                       \
                    --password="{{ yubihsm2_password }}" 
  register:       shell_result
  when:           is_factory_key_exist.stdout == 'true'
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

###############################################################################

- name:           Create test objekt with new password
  shell:          |
                  yubihsm-shell                                               \
                    --action=put-authentication-key                           \
                    --object-id={{ hsm_key.test.id }}                             \
                    --capabilities='all'                                      \
                    --object-type="all"                                       \
                    --delegated="all"                                         \
                    --label="{{ hsm_key.test.label }}"                            \
                    --new-password="{{ hsm_key.test.password }}"                  \
                    --authkey="{{ hsm_key.audit_auth.id }}"                       \
                    --password="{{ hsm_key.audit_auth.password }}"
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output


###############################################################################

- name:           Check test objekt
  shell:          |
                  yubihsm-shell --action=get-object-info                      \
                    --object-id={{ hsm_key.test.id }}                             \
                    --object-type=authentication-key                          \
                    --algorithm=any                                         \
                    --authkey={{ hsm_key.audit_auth.id }}                         \
                    --password="{{ hsm_key.audit_auth.password }}"
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output


###############################################################################

- name:           Delete test object
  shell:          |
                  yubihsm-shell                                               \
                    --action=delete-object                                    \
                    --object-id="{{ hsm_key.test.id }}"                           \
                    --object-type="authentication-key"                        \
                    --authkey="{{ hsm_key.audit_auth.id }}"                       \
                    --password="{{ yubihsm2_password }}" 
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output