---

- name:           Soft factory reset
  shell:          |
                  yubihsm-shell                                               \
                  --action=reset                                              \
                  --domains={{ main_domain }}                                 \
                  --authkey={{ hsm_key.audit_auth.id }}                       \
                  --password="{{ hsm_key.audit_auth.password }}"
  register:       shell_result
  when:           debug_output
  ignore_errors: "{{ debug_output }}"

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

###############################################################################
