---

interpreter_python:         "/usr/bin/python"  
debug_output:               true

vm_01:                      "20.52.144.237"
vm_02:                      "20.52.144.148"
vm_03:                      "20.52.144.178"
vm_04:                      "20.52.144.213"

root_ca_ip:                 "{{ vm_01 }}"
policy_ca_staff_ip:         "{{ vm_01 }}"
policy_ca_service_ip:       "{{ vm_01 }}"
issue_ca_staff_ip:          "{{ vm_02 }}"
issue_ca_service_ip:        "{{ vm_03 }}"
foo_dum_my_ip:              "{{ vm_04 }}"
bar_dum_my_ip:              "{{ vm_04 }}"
baz_dum_my_ip:              "{{ vm_04 }}"
jane_doe_ip:                "{{ vm_02 }}"
john_doe_ip:                "{{ vm_02 }}"
# ansible_git_checkout_ip:    "local"
# azure_control_server_ip:    "local"

ansible_user:               dummy
ansible_become:             yes


pki_workspace:              "/srv/pki"
pki_ca_dir:                 "{{ pki_workspace }}/ca"
pki_csr_local_dir:          "{{ pki_workspace }}/csr"
pki_end_entities_dir:       "{{ pki_workspace }}/end_entities"

pki_key_password:           "fake"
pki_csr_exchange_port:      "8011"
pki_root_ca_cert:           "root-ca-01.dum.my.crt.pem"

pki_country_name:           "DE"
pki_state_or_province_name: "Dummyfild"
pki_city_name:              "Dummy Town"
pki_organization_name:      "Dummy GmbH"