---

- name:        Download signing certificate files of end entity / services
  get_url:
    url:       "{{ pki_referrenc_ca_url }}/{{ end_entity.common_name }}.crt.pem"
    dest:      "{{ pki_cert_file }}"
