---

- name: Add a fake seivice in hosts
  lineinfile:
    path:          "/etc/hosts"
    line:          "{{ fake_service_ip }}  {{ fake_service_url }}"
    create: yes

- name: Check service with curl
  shell:           "curl https://{{ fake_service_url }}/index.html"
  ignore_errors: yes
  register:        shell_result
  when:            debug_output

- name: Output return value
  debug:
    msg:           "{{ shell_result }}"
  when:            debug_output

- name: Check service
  get_url:
    url:           https://{{ fake_service_url }}/index.html
    dest:          /tmp/index.html
    client_cert:   "{{ ca_trust_source_dir}}/{{ referrenc_ca_name }}.bundle.pem"
  ignore_errors: yes
  register:        get_url_result
  when:            debug_output

- name: Output return value
  debug:
    msg:           "{{ get_url_result }}"
  when:            debug_output
