---

- name:     Include setup of download trust
  include:  "download_trust.yml"

- name:     Include setup of nginx for the services
  include:  "nginx_radhat.yml"
  when:     ansible_distribution != "Ubuntu"

- name:     Include setup of nginx for the services
  include:  "nginx_ubuntu.yml"
  when:     ansible_distribution == "Ubuntu"