---

- name:     Include setup of trust
  include:  "download_trust.yml"

- name:     Include setup of nginx for the services
  include:  "nginx.yml"
  when:     ansible_distribution != "Ubuntu"

- name:     Include setup of nginx for the services
  include:  "nginx_ubuntu.yml"
  when:     ansible_distribution == "Ubuntu"