---

- name: Create httpd root directory for services
  file:
    path:           "{{ pki_service_http_root_dir }}/{{ fake_service_url }}"
    state:          directory
    owner:          nginx
    group:          nginx
    mode:           'u=rwx,g=rx,o=rx'

- name: Copy index files
  copy:
    src:            index.html
    dest:           "{{ pki_service_http_root_dir }}/{{ fake_service_url }}/index.html"
    owner:          nginx
    group:          nginx
    mode:           'u=xwr,g=xr,o=xr'

- name: Create nginx config for service
  template:
    src:            "{{ fake_service_url }}.conf"
    dest:           "/etc/nginx/conf.d/{{ fake_service_url }}.conf"
    owner:          nginx
    group:          nginx
    mode:           'u=rx,g=r,o=r'

- name: Start service nginx, if not started
  service:
    name:           nginx
    state:          restarted
