---

- name:           Create httpd root directory for services
  file:
    path:         "{{ item }}"
    state:        directory
    mode:         'u=rwx,g=rx,o=rx'
  loop:
    -             "{{ pki_service_http_root_dir }}"
    -             "{{ pki_service_http_root_dir }}/mutual"
    -             "{{ pki_service_http_root_dir }}/company"
    -             "{{ pki_service_http_root_dir }}/oneway"
    -             "{{ pki_service_http_root_dir }}/issuer"

###############################################################################
 
- name:           Copy index files
  copy:
    src:          "{{ item }}-index.html"
    dest:         "{{ pki_service_http_root_dir }}/{{ item }}/index.html"
    mode:         'u=xwr,g=xr,o=xr'
  loop:
    -             "mutual"
    -             "company"
    -             "oneway"
    -             "issuer"
 
###############################################################################

- name:           Create nginx config for service
  template:
    src:          "fake.conf"
    dest:         "/etc/nginx/conf.d/{{ end_entity.common_name }}.conf"
    mode:         'u=rx,g=r,o=r'

- name:           Check nginx config
  shell:          nginx -t
  ignore_errors:  "{{ debug_output }}"
  register:       shell_result
  when:           debug_output

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

###############################################################################

- name:           Start service nginx, if not started
  service:
    name:         nginx
    state:        restarted
  ignore_errors:  "{{ debug_output }}"
