---

- name:           Create httpd root directory for services
  file:
    path:         "{{ item }}"
    state:        directory
    mode:         'u=rwx,g=rx,o=rx'
  loop:
    -             "{{ pki_service_http_root_dir }}"
    -             "{{ pki_service_http_root_dir }}/mutual"
    -             "{{ pki_service_http_root_dir }}/company-mutual"

- name:           Copy index files
  copy:
    src:          index.html
    dest:         "{{ pki_service_http_root_dir }}/index.html"
    mode:         'u=xwr,g=xr,o=xr'

- name:           Copy index files for the mutual section
  copy:
    src:          mutual-index.html
    dest:         "{{ pki_service_http_root_dir }}/mutual/index.html"
    mode:         'u=xwr,g=xr,o=xr'

- name:           Copy index files for the company mutual section
  copy:
    src:          company-mutual.html
    dest:         "{{ pki_service_http_root_dir }}/company-mutual/index.html"
    mode:         'u=xwr,g=xr,o=xr'


- name:           Create nginx config for service
  template:
    src:          "fake.conf"
    dest:         "/etc/nginx/conf.d/{{ end_entity.common_name }}.conf"
    mode:         'u=rx,g=r,o=r'

- name:           Check nginx config
  shell:          nginx -t
  ignore_errors:  "{{ debug_output }}"
  register:       shell_result
  when:           debug_output

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

- name:           Start service nginx, if not started
  service:
    name:         nginx
    state:        restarted
