---


- name: Download certificate signing request files from owner
  get_url:
    url:                      "{{ item.value.owner_url }}/{{ item.key }}.csr.pem"
    dest:                     "{{ pki_csr_local_dir }}/{{ item.key }}.csr.pem"
  with_dict:                  "{{ pki_owner_csr }}"