---

- name: Include setup of trust
  include:  "download_trust.yml"

- name: Include setup of csr
  include:  "download_csr.yml"

- name: Include setup of trust
  include:  "signed_certificate.yml"

- name: Include setup of trust
  include:  "create_bundle.yml"
