---

- name: Download signing certificate files of root ca
  get_url:
    url:            "{{ item.value.referrenc_ca_url }}/root-ca-01.dum.my.crt"
    dest:           "{{ pki_httpd_dir }}/root-ca-01.dum.my.crt"
  with_dict:        "{{ end_entity_csr }}"

- name: Download signing certificate files of issue ca
  get_url:
    url:            "{{ item.value.referrenc_ca_url }}/{{ item.value.ca }}.crt"
    dest:           "{{ pki_ca_dir }}/{{ item.value.ca }}.crt"
  with_dict:        "{{ end_entity_csr }}"

- name: Download Certificate Signing Request files of end_entities_cert
  get_url:
    url:            "{{ item.value.owner_url }}/{{ item.key }}.csr"
    dest:           "{{ pki_csr_local_dir }}/{{ item.key }}.csr"
  with_dict:        "{{ end_entity_csr }}"

- name: Generate a ca signed end entities certificate
  openssl_certificate:
    path:                     "{{ pki_httpd_dir }}/{{ item.key }}.crt"
    csr_path:                 "{{ pki_csr_local_dir }}/{{ item.key }}.csr"
    ownca_path:               "{{ pki_ca_dir }}/{{ item.value.ca }}.crt"
    ownca_privatekey_path:    "{{ pki_ca_dir }}/{{ item.value.ca }}.pem"
    ownca_not_after:          "{{ end_entity_common.not_after }}"
    provider:                 ownca
  with_dict:                  "{{ end_entity_csr }}"
