---

- name: Download Certificate Signing Request files of end_entities_cert
  get_url:
    url:            "{{ item.value.base_url }}/{{ item.key }}.csr"
    dest:           "{{ pki_issue_ca.csr_local_dir }}/{{ item.key }}.csr"
    mode:           '0440'
  with_dict:        "{{ end_entity_csr }}"

- name: Generate a ca signed end entities certificate
  openssl_certificate:
    path:                     "{{ pki_httpd_dir }}/{{ item.key }}.crt"
    csr_path:                 "{{ pki_issue_ca.csr_local_dir }}/{{ item.key }}.csr"
    ownca_path:               "{{ pki_issue_ca.ownca_path }}"
    ownca_privatekey_path:    "{{ pki_issue_ca.ownca_privatekey_path }}"
    ownca_not_after:          "{{ end_entity_common.not_after }}"
    provider:                 ownca
  with_dict:                  "{{ end_entity_csr }}"
