---

- name:            Download root ca certificate files from the referrenc ca (RedHat)
  block:

  - name:          Download
    get_url:
      url:         "{{ referrenc_ca_url }}/{{ pki_root_ca_cert }}"
      dest:        "/usr/share/pki/ca-trust-source/anchors/{{ pki_root_ca_cert }}"
    ignore_errors: "{{ debug_output }}"
    register:      shell_result

  - name:          Output return value
    debug:
      msg:         "{{ shell_result }}"
    when:          debug_output
  when:          ansible_distribution != "Ubuntu"


- name:            Download root ca certificate files from the referrenc ca (Ubuntu)
  block:

  - name:          Download
    get_url:
      url:         "{{ referrenc_ca_url }}/{{ pki_root_ca_cert }}"
      dest:        "/usr/local/share/ca-certificates/{{ pki_root_ca_cert }}.crt"
    ignore_errors: "{{ debug_output }}"
    register:      shell_result

  - name:          Output return value
    debug:
      msg:         "{{ shell_result }}"
    when:          debug_output
  when:          ansible_distribution == "Ubuntu"

###############################################################################

- name:            Download signing certificate files of the end entity / services
  get_url:
    url:           "{{ referrenc_ca_url }}/{{ end_entity.common_name }}.crt.pem"
    dest:          "{{ pki_cert_file }}"