---

- name:            Add a fake seivice in hosts
  lineinfile:
    path:          "/etc/hosts"
    line:          "{{ foo_dum_my_ip }}  {{ fake_service_url }}"
    create: yes


###############################################################################
- name:            Check service with get_url
  get_url:
    url:           https://{{ fake_service_url }}:{{ service_port }}/index.html
    dest:          /tmp/index.html
  ignore_errors:   "{{ debug_output }}"
  register:        get_url_result
  when:            debug_output

- name:            Output return value
  debug:
    msg:           "{{ get_url_result }}"
  when:            debug_output


###############################################################################

- name:            Check service with curl
  shell:           curl https://{{ fake_service_url }}:{{ service_port }}/index.html
  ignore_errors:   "{{ debug_output }}"
  register:        shell_result
  when:            debug_output

- name:            Output return value
  debug:
    msg:           "{{ shell_result }}"
  when:            debug_output

###############################################################################

- name:            Check service with curl with expicit cacert
  shell:           |
                   curl \
                   --cacert /usr/local/share/ca-certificates/{{ pki_root_ca_cert }}.crt \
                   https://{{ fake_service_url }}:{{ service_port }}/index.html
  ignore_errors:   "{{ debug_output }}"
  register:        shell_result
  when:            debug_output

- name:            Output return value
  debug:
    msg:           "{{ shell_result }}"
  when:            debug_output
