---

- name:            Add a fake seivice in hosts
  lineinfile:
    path:          "/etc/hosts"
    line:          "{{ foo_dum_my_ip }}  {{ fake_service_url }}"
    create: yes

###############################################################################

- name:            Check service with curl
  shell:           |
                   curl \
                   -v \
                   https://{{ fake_service_url }}:{{ service_port }}/oneway/
  ignore_errors:   "{{ debug_output }}"
  register:        shell_result
  when:            debug_output

- name:            Output return value
  debug:
    msg:           "{{ shell_result }}"
  when:            debug_output

###############################################################################

- name:            Check service with curl with expicit cacert
  shell:           |
                   curl \
                   -v \
                   --cacert /usr/local/share/ca-certificates/{{ pki_root_ca_cert }}.crt \
                   https://{{ fake_service_url }}:{{ service_port }}/oneway/index.html
  ignore_errors:   "{{ debug_output }}"
  register:        shell_result
  when:            debug_output

- name:            Output return value
  debug:
    msg:           "{{ shell_result }}"
  when:            debug_output

###############################################################################

- name:            Check service with curl with simple mutual tls
  shell:           |
                   curl \
                   -v \
                   --cacert {{ pki_publication_dir }}/{{ pki_root_ca_cert }} \
                   --key {{ pki_priv_key }} \
                   --cert {{ pki_bundle_file }} \
                   https://{{ fake_service_url }}:{{ service_port }}/mutual/index.html
  ignore_errors:   "{{ debug_output }}"
  register:        shell_result
  when:            debug_output

- name:            Output return value
  debug:
    msg:           "{{ shell_result }}"
  when:            debug_output

################################################################################

- name:            Check service with curl with enhanced mutual tls
  shell:           |
                   curl \
                   -v \
                   --cacert {{ pki_publication_dir }}/{{ pki_root_ca_cert }} \
                   --key {{ pki_priv_key }} \
                   --cert {{ pki_bundle_file }} \
                   https://{{ fake_service_url }}:{{ service_port }}/company/index.html
  ignore_errors:   "{{ debug_output }}"
  register:        shell_result
  when:            debug_output

- name:            Output return value
  debug:
    msg:           "{{ shell_result }}"
  when:            debug_output


###############################################################################

- name:            Check service with curl with mutual tls issuer rule
  shell:           |
                   curl \
                   -v \
                   --cacert {{ pki_publication_dir }}/{{ pki_root_ca_cert }} \
                   --key {{ pki_priv_key }} \
                   --cert {{ pki_bundle_file }} \
                   https://{{ fake_service_url }}:{{ service_port }}/issuer/index.html
  ignore_errors:   "{{ debug_output }}"
  register:        shell_result
  when:            debug_output

- name:            Output return value
  debug:
    msg:           "{{ shell_result }}"
  when:            debug_output
