---

ansible_host:                     "{{ bar_dum_my_ip }}"

pki_referrenc_ca_url:             "http://{{ issue_ca_service_ip }}:{{ pki_csr_exchange_port }}"
pki_service_http_root_dir:        "/srv/http"



end_entity:
    common_name:              "bar.dum.my"
    email_address:            "service-ca@dum.my"
    country_name:             "{{ pki_country_name }}"
    state_or_province_name:   "{{ pki_state_or_province_name }}"
    city_name:                "{{ pki_city_name }}"
    organization_name:        "{{ pki_organization_name }}"
    organizational_unit_name: "barbar service department"
    not_after:                "+26w"
    key_usage_req:            "nonRepudiation, digitalSignature, keyEncipherment"
    key_usage_ca:             "critical, digitalSignature, cRLSign, keyCertSign"

pki_private_dir:              "{{ pki_workspace }}/{{ end_entity.common_name }}"
pki_opensslconfig:            "{{ pki_private_dir }}/openssl.cnf"
pki_priv_key:                 "{{ pki_private_dir }}/private/{{ end_entity.common_name }}.key.pem"
pki_password_file:            "{{ pki_private_dir }}/keypassword.txt"
pki_serial_file:              "{{ pki_private_dir }}/serial"
pki_index_file:               "{{ pki_private_dir }}/index"
pki_crlnumber_file:           "{ pki_private_dir }}/crlnumber"
pki_cert_file:                "{{ pki_ca_dir }}/{{ end_entity.common_name }}.crt.pem"
pki_csr_file:                 "{{ pki_publication_dir }}/{{ end_entity.common_name }}.csr.pem"
