---

ansible_host:                 "{{ foo_dum_my_ip }}"

referenc_ca_url:             "http://{{ issue_ca_service_ip }}:{{ pki_csr_exchange_port }}"
referenc_ca_name:            "service-issue-ca-01.dum.my"

end_entity:
    common_name:              "foo.dum.my"
    email_address:            "service-ca@dum.my"
    country_name:             "{{ pki_country_name }}"
    state_or_province_name:   "{{ pki_state_or_province_name }}"
    city_name:                "{{ pki_city_name }}"
    organization_name:        "{{ pki_organization_name }}"
    organizational_unit_name: "Foobar service department"
    not_after_days:           "90"
    key_usage_req:            "nonRepudiation, digitalSignature, keyEncipherment"
    key_usage_ca:             "critical, digitalSignature, cRLSign, keyCertSign"


accepted_organizational_unit: "OU=Foobar staff department"
non_accepted_issuer_ca:
    -                         "CN=staff-issue-ca-00.fondsfinanz.de"
    -                         "CN=staff-issue-ca-02.fondsfinanz.de"
    -                         "CN=staff-issue-ca-03.fondsfinanz.de"

