---

ansible_host:                 "{{ foo_dum_my_ip }}"

referrenc_ca_url:             "http://{{ issue_ca_service_ip }}:{{ pki_csr_exchange_port }}"
referrenc_ca_name:            "service-issue-ca-01.dum.my"

end_entity:
    common_name:              "foo.dum.my"
    email_address:            "service-ca@dum.my"
    country_name:             "{{ pki_country_name }}"
    state_or_province_name:   "{{ pki_state_or_province_name }}"
    city_name:                "{{ pki_city_name }}"
    organization_name:        "{{ pki_organization_name }}"
    organizational_unit_name: "Foobar service department"
    not_after_days:           "90"
    key_usage_req:            "nonRepudiation, digitalSignature, keyEncipherment"
    key_usage_ca:             "critical, digitalSignature, cRLSign, keyCertSign"

# Date format example: "Jan 19 09:02:19 2021 GMT"
# A RegEx is needed here
#
# Allow any date:
# "^([A-Z|a-z]{3}) ([0-9][0-9]) ([0-9][0-9]):([0-9][0-9]):([0-9][0-9]) ([0-9][0-9][0-9][0-9]) GMT$"
#
# Must have been created in 2020:
# "^([A-Z|a-z]{3}) ([0-9][0-9]) ([0-9][0-9]):([0-9][0-9]):([0-9][0-9]) 2020 GMT$"
#
# Must have been created in January 2020:
# "^Jan ([0-9][0-9]) ([0-9][0-9]):([0-9][0-9]):([0-9][0-9]) 2020 GMT$"
#
# Must have been created in January or February 2020:
# "^(Jan|Feb) ([0-9][0-9]):([0-9][0-9]):([0-9][0-9]) 2020 GMT$"

accepted_cert_start_date:     "^([A-Z|a-z]{3}) ([0-9][0-9]) ([0-9][0-9]):([0-9][0-9]):([0-9][0-9]) 202([0-9]) GMT$"

# The same like accepted_cert_start_date but negated!

not_accepted_cert_start_date: "^([A-Z|a-z]{3}) ([0-9][0-9]) ([0-9][0-9]):([0-9][0-9]):([0-9][0-9]) 2019 GMT$"

# Restrict access to departments

accepted_organizational_unit: "OU=Foobar staff department"
