---

ansible_host:               "{{ root_ca_ip }}"

referrenc_ca_url:           "http://{{ root_ca_ip }}:{{ pki_csr_exchange_port }}"
referrenc_ca_name:          "root-ca-01.dum.my"

root_ca:                    true
pki_root_ca:
  common_name:              "root-ca-01.dum.my"
  email_address:            "ca-admin@dum.my"
  country_name:             "DE"
  state_or_province_name:   "Dummyfild"
  city_name:                "Dummy Town"
  organization_name:        "Dummy GmbH"
  organizational_unit_name: "Security department"
  not_after_days:           "9125"
  key_usage_req:            "nonRepudiation, digitalSignature, keyEncipherment"
  key_usage_ca:             "critical, digitalSignature, cRLSign, keyCertSign"

pki_owner_csr:
  "staff-policy-ca-01.dum.my":
      owner_url:           "http://{{ policy_ca_staff_ip }}:{{ pki_csr_exchange_port }}"
      not_after_days:      "365"
  "service-policy-ca-01.dum.my":
      owner_url:           "http://{{ policy_ca_service_ip }}:{{ pki_csr_exchange_port }}"
      not_after_days:      "365"