---

ansible_host:                 "{{ issue_ca_service_ip }}"

referrenc_ca_url:             "http://{{ policy_ca_service_ip }}:{{ pki_csr_exchange_port }}"
referrenc_ca_name:            "service-policy-ca-01.dum.my"

pki_intermediate_ca:
    common_name:              "service-issue-ca-01.dum.my"
    email_address:            "service-ca@dum.my"
    country_name:             "{{ pki_country_name }}"
    state_or_province_name:   "{{ pki_state_or_province_name }}"
    city_name:                "{{ pki_city_name }}"
    organization_name:        "{{ pki_organization_name }}"
    organizational_unit_name: "Service department"
    not_after_days:           "180"
    key_usage_req:            "nonRepudiation, digitalSignature, keyEncipherment"
    key_usage_ca:             "critical, digitalSignature, cRLSign, keyCertSign"
    pathlen:                  "5"


pki_owner_csr:
    "foo.dum.my":
        owner_url:           "http://{{ foo_dum_my_ip }}:{{ pki_csr_exchange_port }}"
        not_after_days:      "90"
    "bar.dum.my":
        owner_url:           "http://{{ bar_dum_my_ip }}:{{ pki_csr_exchange_port }}"
        not_after_days:      "90"
    "baz.dum.my":
        owner_url:           "http://{{ baz_dum_my_ip }}:{{ pki_csr_exchange_port }}"
        not_after_days:      "90"
