---

ansible_host:                 "{{ issue_ca_staff_ip }}"

referenc_ca_url:             "http://{{ policy_ca_staff_ip }}:{{ pki_csr_exchange_port }}"
referenc_ca_name:            "staff-policy-ca-01.dum.my"

pki_intermediate_ca:
    common_name:              "staff-issue-ca-01.dum.my"
    email_address:            "staff-ca@dum.my"
    country_name:             "{{ pki_country_name }}"
    state_or_province_name:   "{{ pki_state_or_province_name }}"
    city_name:                "{{ pki_city_name }}"
    organization_name:        "{{ pki_organization_name }}"
    organizational_unit_name: "staff department"
    not_after_days:           "180"
    key_usage_req:            "nonRepudiation, digitalSignature, keyEncipherment"
    key_usage_ca:             "critical, digitalSignature, cRLSign, keyCertSign"
    pathlen:                  "0"

pki_owner_csr:
    "jane.doe":
        owner_url:           "http://{{ jane_doe_ip }}:{{ pki_csr_exchange_port }}"
        not_after_days:      "90"
    "john.doe":
        owner_url:           "http://{{ john_doe_ip }}:{{ pki_csr_exchange_port }}"
        not_after_days:      "90"