---

all:
  children:
    pki:
      children:
        pki_root_ca:
          hosts:
            vm01:
        pki_policy_ca:
          hosts:
            vm01:
        pki_issue_ca:
          hosts:
            vm03:
            vm02:
        pki_end_entity:
          hosts:
            vm04:
        pki_fake_service:
          hosts:
            vm04:
        pki_ansible:
          hosts:
            localhost:
