
# [pki:children]
# pki_root_ca
# pki_issue_ca
# pki_end_entity

# [pki_root_ca]
# vm01 ansible_host=192.168.178.76

# [pki_policy_ca]
# vm01 ansible_host=192.168.178.76

# [pki_issue_ca]
# vm03 ansible_host=192.168.178.78
# vm02 ansible_host=192.168.178.77

# [pki_end_entity]
# vm04 ansible_host=192.168.178.26
# #######################################################

all:
  children:
    pki:
      children:
        pki_root_ca:
          hosts:
            vm01:
        pki_policy_ca:
          hosts:
            vm01:
        pki_issue_ca:
          hosts:
            vm03:
            vm02:
        pki_end_entity:
          hosts:
            vm04:

# all:
#     hosts:
#       mail.example.com:
#     children:
#       webservers:
#         hosts:
#           foo.example.com:
#           bar.example.com:
#       dbservers:
#         hosts:
#           one.example.com:
#           two.example.com:
#           three.example.com: