---

- hosts: pki_offline_ca
  roles:
    - pki_root_ca
    - pki_policy_ca
    - pki_issue_ca
    - pki_fetch_issue_ca_files

# - hosts: pki_online_ca
#   roles:
#     - pki_end_entity_staff
#     - pki_end_entity_service


- hosts: pki_end_entity_staff
  roles:
    - pki_end_entity_staff

- hosts: pki_end_entity_service
  roles:
    - pki_end_entity_service