---

# - name: Preparation of all nodes for their job
#   hosts: pki
#   roles:
#     - pki_pre_install

- name: Creating CSRs for the issue ca
  hosts: pki_end_entity
  roles:
    - pki_end_entity_csr

- name: Creating CSRs for the end entities
  hosts: pki_end_entity_csr
  roles:
    - pki_end_entity_csr

- name: Signed issue ca cert
  hosts: pki_policy_ca
  roles:
    - pki_signed_issue_cert

- name: Signed end entities cert
  hosts: pki_issue_ca
  roles:
    - pki_signed_end_entities_cert



##############################################################
##############################################################


# - hosts: pki_offline_ca
#   roles:
#     - pki_root_ca
#     - pki_policy_ca
#     - pki_issue_ca

# - hosts: pki_fetch_issue_ca_files
#   roles:
#   - pki_fetch_issue_ca_files

# - hosts: pki_end_entity_staff
#   roles:
#     - pki_end_entity_staff

# - hosts: pki_end_entity_service
#   roles:
#     - pki_end_entity_service