---

- name:                               Set individual pathes and other things for root_ca
  block:
    - set_fact:
        pki_private_dir:              "{{ pki_workspace }}/{{ pki_root_ca.common_name }}"

    - set_fact:
        pki_opensslconfig:            "{{ pki_private_dir }}/openssl.cnf"
        pki_priv_key:                 "{{ pki_private_dir }}/private/{{ pki_root_ca.common_name }}.key.pem"
        pki_serial_file:              "{{ pki_private_dir }}/serial"
        pki_index_file:               "{{ pki_private_dir }}/index"
        pki_crlnumber_file:           "{{ pki_private_dir }}/crlnumber"
        pki_cert_file:                "{{ pki_ca_dir }}/{{ pki_root_ca.common_name }}.crt.pem"
        pki_index_attr_file:          "{{ pki_private_dir }}/index.attr"
        pki_bundle_file:              "{{ pki_publication_dir }}/{{ pki_root_ca.common_name }}.bundle.pem"
  when:                               root_ca is defined

###############################################################################


- name:                               Set individual pathes and other things for intermediate_ca
  block:
    - set_fact:
        pki_private_dir:              "{{ pki_workspace }}/{{ pki_intermediate_ca.common_name }}"

    - set_fact:
        pki_opensslconfig:            "{{ pki_private_dir }}/openssl.cnf"
        pki_priv_key:                 "{{ pki_private_dir }}/private/{{ pki_intermediate_ca.common_name }}.key.pem"
        pki_serial_file:              "{{ pki_private_dir }}/serial"
        pki_index_file:               "{{ pki_private_dir }}/index"
        pki_crlnumber_file:           "{{ pki_private_dir }}/crlnumber"
        pki_cert_file:                "{{ pki_ca_dir }}/{{ pki_intermediate_ca.common_name }}.crt.pem"
        pki_index_attr_file:          "{{ pki_private_dir }}/index.attr"
        pki_bundle_file:              "{{ pki_publication_dir }}/{{ pki_intermediate_ca.common_name }}.bundle.pem"
        pki_csr_file:                 "{{ pki_publication_dir }}/{{ pki_intermediate_ca.common_name }}.csr.pem"
        pki_referrenc_ca_bundle_file: "{{ pki_publication_dir }}/{{ referrenc_ca_name }}.bundle.pem"
  when:
    -                                 pki_intermediate_ca is defined
    -                                 root_ca             is not defined

###############################################################################

- name:                               Set individual pathes and other things for end entity
  block:
  - set_fact:
      pki_private_dir:                "{{ pki_workspace }}/end_entities/{{ end_entity.common_name }}/private"
      # cacheable:                      yes

  - set_fact:
      pki_private_dir:                "{{ pki_workspace }}/end_entities/{{ end_entity.common_name }}/private/"
      pki_opensslconfig:              "{{ pki_private_dir }}/openssl.cnf"
      pki_priv_key:                   "{{ pki_private_dir }}/{{ end_entity.common_name }}.key.pem"
      pki_serial_file:                "{{ pki_private_dir }}/serial"
      pki_index_file:                 "{{ pki_private_dir }}/index"
      pki_crlnumber_file:             "{{ pki_private_dir }}/crlnumber"
      pki_cert_file:                  "{{ pki_private_dir }}/{{ end_entity.common_name }}.crt.pem"
      pki_bundle_file:                "{{ pki_publication_dir }}/{{ end_entity.common_name }}.bundle.pem"
      pki_csr_file:                   "{{ pki_publication_dir }}/{{ end_entity.common_name }}.csr.pem"
      pki_referrenc_ca_bundle_file:   "{{ pki_publication_dir }}/{{ referrenc_ca_name }}.bundle.pem"
      pki_service_http_root_dir:      "/srv/http/{{ end_entity.common_name }}"
  when:                               end_entity is defined
