---

- name: Include setup of nginx for the services
  include:         "nginx.yml"

- name: Add a fake seivice in hosts
  lineinfile:
    path:          "/etc/hosts"
    line:          "192.168.178.26 foo.dum.my"
    create: yes

- name: Check service
  get_url:
    url:           https://foo.dum.my/index.html
    dest:          /tmp/index.html
    client_cert:   "{{ pki_ca_dir }}/root-ca-01.dum.my"
