---

- name: Generate an root Certificate Signing Request
  openssl_csr:
    path:                     "{{ pki_csr_local_dir }}/{{ pki_intermediate_ca.common_name }}.csr"
    privatekey_path:          "{{ pki_ca_dir }}/{{ pki_intermediate_ca.common_name }}.key.pem"
    common_name:              "{{ pki_intermediate_ca.common_name }}"
    country_name:             "{{ pki_intermediate_ca.country_name }}"
    state_or_province_name:   "{{ pki_intermediate_ca.state_or_province_name }}"
    email_address:            "{{ pki_intermediate_ca.email_address }}"
    organization_name:        "{{ pki_intermediate_ca.organization_name }}"
    organizational_unit_name: "{{ pki_intermediate_ca.organizational_unit_name }}"
    key_usage:                "{{ pki_intermediate_ca.key_usage }}"

- name: Check file type
  shell: |
    file {{ pki_csr_local_dir }}/{{ pki_intermediate_ca.common_name }}.csr
  register:                   shell_result
  when:                       debug_output

- name: Output return value
  debug:
    msg:                      "{{ shell_result }}"
  when:                       debug_output