---

- name:    Include fedora support
  include: "fedora_configs.yml"
  when:    ansible_distribution == "Fedora"

- name:    Include CentOS support
  include: "centos_configs.yml"
  when:    ansible_distribution == "CentOS"

- name:    Include nginx setup for fedora & co
  include: "fedora_nginx.yml"
  when:    ansible_distribution != "Ubuntu"

- name:    Include create needed directories for Ubuntu
  include: "ubuntu_create_dirs.yml"
  when:    ansible_distribution == "Ubuntu"

- name:    Include nginx setup for ubuntu
  include: "ubuntu_nginx.yml"
  when:    ansible_distribution == "Ubuntu"
