---

- name:      Install python-apt
  package:
    name:
      -      python-apt
  throttle: 1

- name:      Install needed packages
  package:
    name:
      -      python3-openssl
      -      nginx
  throttle: 1

- name:      Start service nginx, if not started
  service:
    name:    nginx
    state:   started


- name:      Create public directories for ca
  file:
    path:    "{{ item }}"
    state:   directory
    mode:    'u=rwx,g=rx,o=rx'
  loop:
    -        "{{ pki_csr_local_dir }}"
    -        "{{ pki_workspace }}"
    -        "{{ pki_publication_dir }}"

- name:      Create private directories for ca
  file:
    path:    "{{ item }}"
    state:   directory
    mode:    'u=rwx,g=rx,o-rwx'
  loop:
    -        "{{ pki_ca_dir }}"
    -        "{{ pki_end_entities_dir }}"
