---


- name:               Create public directories for ca
  file:
    path:             "{{ item }}"
    state:            directory
    mode:             'u=rwx,g=rx,o=rx'
  loop:
    -                 "{{ pki_csr_local_dir }}"
    -                 "{{ pki_workspace }}"
    -                 "{{ pki_publication_dir }}"

- name:               Create private directories for ca
  file:
    path:             "{{ item }}"
    state:            directory
    mode:             'u=rwx,g=rx,o-rwx'
  loop:
    -                 "{{ pki_ca_dir }}"
    -                 "{{ pki_end_entities_dir }}"
