---

debug_output:               true
ignore_errors:              yes

vm_01:                      "20.52.41.243"
vm_02:                      "20.52.41.152"
vm_03:                      "20.52.41.88"
vm_04:                      "20.52.41.223"
vm_05:                      "51.116.186.241"
vm_06:                      "51.116.187.148"
vm_07:                      "20.52.41.92"


root_ca_ip:                 "{{ vm_01 }}"
policy_ca_staff_ip:         "{{ vm_02 }}"
policy_ca_service_ip:       "{{ vm_03 }}"
issue_ca_staff_ip:          "{{ vm_04 }}"
issue_ca_service_ip:        "{{ vm_05 }}"
jane_doe_ip:                "{{ vm_06 }}"
john_doe_ip:                "{{ vm_06 }}"
foo_dum_my_ip:              "{{ vm_07 }}"
bar_dum_my_ip:              "{{ vm_07 }}"
baz_dum_my_ip:              "{{ vm_07 }}"
# ansible_git_checkout_ip:    "local"
# azure_control_server_ip:    "local"

ansible_user:               dummy
ansible_become:             yes

pki_workspace:              "/srv/pki"
pki_publication_dir:        "/srv/pki/html"
pki_ca_dir:                 "{{ pki_workspace }}/ca"
pki_csr_local_dir:          "{{ pki_workspace }}/csr"
pki_end_entities_dir:       "{{ pki_workspace }}/end_entities"

pki_key_password:           "fake"
pki_csr_exchange_port:      "8011"
pki_root_ca_cert:           "root-ca-01.dum.my.crt.pem"

pki_country_name:           "DE"
pki_state_or_province_name: "Dummyfild"
pki_city_name:              "Dummy Town"
pki_organization_name:      "Dummy GmbH"