- name: Generate end user private key
  openssl_privatekey:
    path: "{{ workspace_pki }}/{{ end_user_priv_key }}"

- name: Generate an OpenSSL Certificate Signing Request for end user
  openssl_csr:
      path: "{{ workspace_pki }}/{{ end_user_csr }}"
      privatekey_path: "{{ workspace_pki }}/{{ end_user_priv_key }}"
      common_name: "enduser-001"
      key_usage:
        - digitalSignature
        - keyAgreement
      extended_key_usage:
        - clientAuth

- debug:
    msg: "Path: {{ item }}"
  loop:
    - "{{ workspace_pki }}"
    - "{{ end_user_crt }}"
    - "{{ root_ca_priv_key }}"
    - "{{ end_user_csr }}"

- name: Generate a ca Signed OpenSSL user certificate
  openssl_certificate:
    path: "{{ workspace_pki }}/{{ end_user_crt }}"
    csr_path: "{{ workspace_pki }}/{{ end_user_csr }}"
    # privatekey_path: "{{ workspace_pki }}/{{ root_ca_priv_key }}"
    # entrust_not_after: "+30d"
    # ownca_not_after: "+30d"
    # not_after: "+30d"
    ownca_path: "{{ workspace_pki }}/{{ root_crt }}"
    ownca_privatekey_path: "{{ workspace_pki }}/{{ root_ca_priv_key }}"
    provider: ownca


# - name: Generate an OpenSSL certificate signed with your own CA certificate
#   openssl_certificate:
#       path: /etc/ssl/crt/ansible.com.crt
#       csr_path: /etc/ssl/csr/ansible.com.csr
#       ownca_path: /etc/ssl/crt/ansible_CA.crt
#       ownca_privatekey_path: /etc/ssl/private/ansible_CA.pem
#       provider: ownca