---

- name:           Create csr file
  shell: |
                  openssl req \
                  -new \
                  -sha256 \
                  -nodes \
                  -config {{ pki_opensslconfig }} \
                  -key {{ pki_priv_key }} \
                  -out {{ pki_csr_file }}
  args:
    chdir:        "{{ pki_private_dir }}"
    creates:      "{{ pki_csr_file }}"
  register:       shell_result
  ignore_errors:  "{{ debug_output }}"
  when:           debug_output

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output
