---

- name:       Generate an root ca private key
  shell: |
              openssl genrsa \
              -passout file:{{ pki_password_file }} \
              -out {{ pki_priv_key }}
  args:
    chdir:    "{{ pki_private_dir }}"
    creates:  "{{ pki_priv_key }}"
  ignore_errors: "{{ debug_output }}"
  register:      shell_result

- name:          Output return value
  debug:
    msg:         "{{ shell_result }}"
  when:          debug_output

