---

- name: Create csr file
  shell: |
    openssl req \
    -new \
    -sha256 \
    -nodes \
    -config {{ pki_opensslconfig }} \
    -key {{ pki_priv_key }} \
    -out {{ pki_csr_file }}
  args:
    chdir:   "{{ pki_private_dir }}"
    creates: "{{ pki_csr_file }}"

- name: Check file type of csr file
  shell: |
    file {{ pki_csr_file }}
  register:                   shell_result
  when:                       debug_output

- name: Output return value
  debug:
    msg:                      "{{ shell_result }}"
  when:                       debug_output

- name: Check index file
  shell: |
    cat  {{ pki_private_dir }}/index.txt
  register:                   shell_result
  when:                       debug_output

- name: Output return value
  debug:
    msg:                      "{{ shell_result }}"
  when:                       debug_output
