---

- name:            Create a base directory for policy ca
  file:
    path:          "{{ pki_repo_dest }}"
    state:         absent

- name:            Check the fingerprint of the commit sign
  git:
    repo:          "{{ pki_repo }}"
    dest:          "{{ pki_repo_dest }}"
    version:       "{{ pki_git_tag }}"
    force:         yes
    gpg_whitelist: "{{ pki_gpg_whitelist }}"
    verify_commit: true
