---

all:
  children:
    pki:
      children:
        pki_root_ca:
          hosts:
            root_ca:
        pki_policy_ca:
          hosts:
            policy_ca_service:
            policy_ca_staff:
        pki_issue_ca:
          hosts:
            issue_ca_service:
            issue_ca_staff:
        pki_end_entity:
          children:
            end_entity_service:
              hosts:
                foo.dum.my:
                bar.dum.my:
                baz.dum.my:
            end_entity_staff:
              hosts:
                # jane.doe:
                # john.doe:
        pki_fake_service:
          hosts:
            foo.dum.my:
            # fake_service:
        pki_fake_client:
          hosts:
            fake_client:

    pki_ansible:
      hosts:
        ansible_git_checkout:
    pki_azure_deploy:
      hosts:
        azure_control_server:
