---

all:
  children:
    pki:
      children:
        pki_root_ca:
          hosts:
            root-ca-01.dum.my:
        pki_policy_ca:
          hosts:
            service-policy-ca-01.dum.my:
            staff-policy-ca-01.dum.my:
        pki_issue_ca:
          hosts:
            service-issue-ca-01.dum.my:
            staff-issue-ca-01.dum.my:
        pki_end_entity:
          children:
            end_entity_service:
              hosts:
                foo.dum.my:
                bar.dum.my:
                baz.dum.my:
            end_entity_staff:
              hosts:
                jane.doe:
                john.doe:
        pki_fake_service:
          hosts:
            foo.dum.my:
        pki_fake_client:
          hosts:
            jane.doe:
            john.doe:
    local_control_host:
      hosts:
        ansible.dum.my:
        azure-control.dum.my:
        yubihsm2.host:
 
