---

all:
  children:
    pki:
      children:
        pki_root_ca:
          hosts:
            root_ca:
        pki_policy_ca:
          hosts:
            policy_ca_service:
            policy_ca_staff:
        pki_issue_ca:
          hosts:
            issue_ca_service:
            issue_ca_staff:
        pki_end_entity:
          hosts:
            end_entity_service:
            end_entity_staff:
        pki_fake_service:
          hosts:
            fake_service:
    pki_ansible:
      hosts:
        ansible_git_checkout:
    pki_azure_deploy:
      hosts:
        azure_control_server:
