---

- name: Download signing certificate files from the referrenc ca
  get_url:
    url:                      "{{ referrenc_ca_url }}/{{ pki_intermediate_ca.common_name }}.crt.pem"
    dest:                     "{{ pki_ca_dir }}/{{ pki_intermediate_ca.common_name }}.crt.pem"

- name: Download certificate signing request files from owner
  get_url:
    url:                      "{{ item.value.owner_url }}/{{ item.key }}.csr"
    dest:                     "{{ pki_csr_local_dir }}/{{ item.key }}.csr"
  with_dict:                  "{{ pki_owner_csr }}"

- name: Generate a ca signed certificate
  openssl_certificate:
    path:                     "{{ pki_httpd_dir }}/{{ item.key }}.crt.pem"
    csr_path:                 "{{ pki_csr_local_dir }}/{{ item.key }}.csr"
    ownca_path:               "{{ pki_ca_dir }}/{{ pki_intermediate_ca.common_name }}.crt.pem"
    ownca_privatekey_path:    "{{ pki_ca_dir }}/{{ pki_intermediate_ca.common_name }}.key.pem"
    ownca_not_after:          "{{ item.value.not_after }}"
    provider:                 ownca
  with_dict:                  "{{ pki_owner_csr }}"

- name: Check file type
  shell: |
    file {{ pki_httpd_dir }}/{{ item.key }}.crt.pem
  register:                   shell_result
  when:                       debug_output
  with_dict:                  "{{ pki_owner_csr }}"

- name: Output return value
  debug:
    msg:                      "{{ shell_result }}"
  when:                       debug_output

- name: Verify the intermediate certificate
  shell: |
    openssl verify \
    -CAfile  {{ pki_ca_dir }}/{{ referrenc_ca_name }}.crt.pem \
     {{ pki_httpd_dir }}/{{ item.key }}.crt.pem
  with_dict:                  "{{ pki_owner_csr }}"
  ignore_errors: yes
  register:                   shell_result
  when:                       debug_output

- name: Output return value
  debug:
    msg:                      "{{ shell_result }}"
  when:                       debug_output

- name: Set owner of crt file
  file:
    path:                     "{{ pki_httpd_dir }}/{{ item.key }}.crt.pem"
    owner:                    nginx
    group:                    nginx
    mode:                     'u=rw,g=r,o=r'
  with_dict:                  "{{ pki_owner_csr }}"

- name: Create XXXXX.bundle.cert.pem
  shell: |
    cat {{ pki_httpd_dir }}/{{ referrenc_ca_name }}.bundle.pem \
        {{ pki_ca_dir }}/{{ pki_intermediate_ca.common_name }}.crt.pem \
    > {{ pki_httpd_dir }}/{{ pki_intermediate_ca.common_name }}.bundle.pem

- name: Set owner of bundle file
  file:
    path:                     "{{ pki_httpd_dir }}/{{ pki_intermediate_ca.common_name }}.bundle.pem"
    owner:                    nginx
    group:                    nginx
    mode:                     'u=rw,g=r,o=r'

- name: Check dummy-ca-chain-bundle.cert.pem
  shell: |
    openssl verify -CAfile {{ pki_ca_dir }}/{{ referrenc_ca_name }}.crt.pem \
    {{ pki_httpd_dir }}/dummy-ca-chain-bundle.pem
  register:                   check_result
  with_dict:                  "{{ pki_owner_csr }}"
  when:                       debug_output
  ignore_errors: yes

- name: Output return value
  debug:
    msg:                      "{{ shell_result }}"
  when:                       debug_output
