---

- name: Create a base directory for policy ca
  file:
    path:    "{{ item }}"
    state:   absent
  loop:
    - "{{ pki_workspace }}"
    - "{{ pki_ca_dir }}"
    - "{{ pki_csr_local_dir }}"
    - "{{ pki_end_entities_dir }}"
    - "{{ pki_httpd_dir }}"
    - "/etc/nginx/conf.d/foo.dum.my.conf"
