---

###############################################################################

- name:           Check file type of csr file
  shell: |
                  file {{ pki_csr_file }}
  register:       shell_result
  when:           debug_output

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output

###############################################################################

- name:           Check index file
  shell: |
                  cat  {{ pki_index_file }}
  register:       shell_result
  when:           debug_output

- name:           Output return value
  debug:
    msg:          "{{ shell_result }}"
  when:           debug_output