---

all:
  children:
    pki:
      children:
        pki_root_ca:
          hosts:
            root-ca-01.dum.my:
        pki_policy_ca:
          hosts:
            service-policy-ca-01.dum.my:
            staff-policy-ca-01.dum.my:
        pki_issue_ca:
          hosts:
            service-issue-ca-01.dum.my:
            staff-issue-ca-01.dum.my:
        pki_end_entity:
          children:
            end_entity_service:
              hosts:
                foo.dum.my:
                bar.dum.my:
                baz.dum.my:
            end_entity_staff:
              hosts:
                # jane.doe:
                # john.doe:
        pki_fake_service:
          hosts:
            foo.dum.my:
            # fake_service:
        pki_fake_client:
          hosts:
            # fake_client:
            fake-client.dum.my:

    pki_ansible:
      hosts:
        # ansible_git_checkout:
        ansible.dum.my:
    pki_azure_deploy:
      hosts:
        # azure_control_server:
        azure-control.dum.my:
