---

ansible_host: "{{ issue_ca_service_ip }}"

referrenc_ca_url:  "http://{{ policy_ca_service_ip }}:{{ pki_csr_exchange_port }}"
referrenc_ca_name: "service-policy-ca-01.dum.my"

pki_intermediate_ca:
    common_name:              "service-issue-ca-01.dum.my"
    email_address:            "service-ca@dum.my"
    country_name:             "{{ pki_country_name }}"
    state_or_province_name:   "{{ pki_state_or_province_name }}"
    organization_name:        "{{ pki_organization_name }}"
    organizational_unit_name: "Service department"
    not_after:                "+26w"
    key_usage:
        - digitalSignature
        - keyAgreement

pki_owner_csr:
  "foo.dum.my":
      owner_url:        "http://{{ end_entity_service_ip }}:{{ pki_csr_exchange_port }}"
      not_after:        "+26w"
  "bar.dum.my":
      owner_url:        "http://{{ end_entity_service_ip }}:{{ pki_csr_exchange_port }}"
      not_after:        "+26w"
  "baz.dum.my":
      owner_url:        "http://{{ end_entity_service_ip }}:{{ pki_csr_exchange_port }}"
      not_after:        "+26w"
