---

ansible_host:               "{{ policy_ca_service_ip }}"

referrenc_ca_url:           "http://{{ root_ca_ip }}:{{ pki_csr_exchange_port }}"
referrenc_ca_name:          "root-ca-01.dum.my"

pki_intermediate_ca:
    common_name:              "service-policy-ca-01.dum.my"
    email_address:            "service-ca@dum.my"
    country_name:             "{{ pki_country_name }}"
    state_or_province_name:   "{{ pki_state_or_province_name }}"
    city_name:                "{{ pki_city_name }}"
    organization_name:        "{{ pki_organization_name }}"
    organizational_unit_name: "Security department"
    not_after:                "+26w"
    key_usage:
        - digitalSignature
        - keyAgreement

pki_private_dir:       "{{ pki_workspace }}/{{ pki_intermediate_ca.common_name }}"
pki_opensslconfig:     "{{ pki_private_dir }}/openssl.cnf"
pki_priv_key:          "{{ pki_private_dir }}/private/{{ pki_intermediate_ca.common_name }}.key.pem"
pki_password_file:     "{{ pki_private_dir }}/keypassword.txt"
pki_serial_file:       "{{ pki_private_dir }}/serial"
pki_index_file:        "{{ pki_private_dir }}/index"
pki_crlnumber_file:    "{ pki_private_dir }}/crlnumber"
pki_cert_file:         "{{ pki_publication_dir }}/{{ pki_intermediate_ca.common_name }}.crt.pem"
pki_csr_file:          "{{ pki_publication_dir }}/{{ pki_intermediate_ca.common_name }}.csr.pem"

pki_owner_csr:
    "service-issue-ca-01.dum.my":
        owner_url:     "http://{{ issue_ca_service_ip }}:{{ pki_csr_exchange_port }}"
        not_after:     "+26w"
### EXAMPLE
# "service-issue-ca-02.dum.my":
#     owner_url:        "http://{{ issue_ca_service_ip }}:{{ pki_csr_exchange_port }}"
#     not_after:        "+26w"
