# Policy CA & Root CA
---

pki_policy_ca_common:
    country_name:             "DE"
    state_or_province_name:   "Dummyfild"
    organization_name:        "Dummy GmbH"

root_ca:
    common_name:              "root-ca-01.dum.my"
    country_name:             "DE"
    state_or_province_name:   "Dummyfild"
    email_address:            "ca-admin@dum.my"
    organization_name:        "Dummy GmbH"
    organizational_unit_name: "Security department"
    not_after:                "+1300w"
    key_usage:
        - digitalSignature
        - keyAgreement

pki_policy_ca:
    "staff-policy-ca-01.dum.my":
        email_address:            "staff-ca@dum.my"
        organizational_unit_name: "Security department"
        not_after:                "+52w"
        key_usage:
            - digitalSignature
            - keyAgreement
    "service-policy-ca-01.dum.my":
        email_address:            "service-ca@dum.my"
        organizational_unit_name: "Security department"
        not_after:                "+26w"
        key_usage:
            - digitalSignature
            - keyAgreement

pki_policy_ca_csr:
    "staff-policy-ca-01.dum.my":
        owner_url:        "http://192.168.178.76"
        referrenc_ca_url: "http://192.168.178.76"
        ca:               "root-ca-01.dum.my"
        not_after:        "+52w"
    "service-policy-ca-01.dum.my":
        owner_url:        "http://192.168.178.76"
        referrenc_ca_url: "http://192.168.178.76"
        ca:               "root-ca-01.dum.my"
        not_after:        "+26w"

pki_issue_ca_csr:
    "staff-issue-ca-01.dum.my":
        owner_url:        "http://192.168.178.77"
        referrenc_ca_url: "http://192.168.178.76"
        ca:               "staff-policy-ca-01.dum.my"
        not_after:        "+52w"
    "staff-issue-ca-02.dum.my":
        owner_url:        "http://192.168.178.77"
        referrenc_ca_url: "http://192.168.178.76"
        ca:               "staff-policy-ca-01.dum.my"
        not_after:        "+52w"
    "service-issue-ca-01.dum.my":
        owner_url:        "http://192.168.178.78"
        referrenc_ca_url: "http://192.168.178.76"
        ca:               "service-policy-ca-01.dum.my"
        not_after:        "+26w"
    "service-issue-ca-02.dum.my":
        owner_url:        "http://192.168.178.78"
        referrenc_ca_url: "http://192.168.178.76"
        ca:               "service-policy-ca-01.dum.my"
        not_after:        "+26w"
