---
# Staff issue CA

ansible_host: "192.168.178.77"

pki_issue_ca_common:
    country_name:             "DE"
    state_or_province_name:   "Dummyfild"
    organization_name:        "Dummy GmbH"

pki_issue_ca:
    "staff-issue-ca-01.dum.my":
        email_address:            "staff-ca@dum.my"
        organizational_unit_name: "staff department"
        not_after:                "+26w"
        key_usage:
            - digitalSignature
            - keyAgreement
    "staff-issue-ca-02.dum.my":
        email_address:            "staff-ca@dum.my"
        organizational_unit_name: "staff department"
        not_after:                "+26w"
        key_usage:
            - digitalSignature
            - keyAgreement

end_entity_common:
    owner_url:                "http://192.168.178.26:{{ pki_csr_exchange_port }}"
    referrenc_ca_url:         "http://192.168.178.78:{{ pki_csr_exchange_port }}"
    not_after:                "+26w"
    country_name:             "DE"
    state_or_province_name:   "Dummyfild"
    organization_name:        "Dummy GmbH"

end_entity_csr: []
    ## EXAPLE:
    # "jane.doe@dum.my":
    #     owner_url:        "{{ end_entity_common.owner_url }}"
    #     referrenc_ca_url: "{{ end_entity_common.referrenc_ca_url }}"
    #     ca:               "staff-issue-ca-01.dum.my"
    #     email_address:    "jane.doe@dum.my"
    # "john.doe":
    #     owner_url:        "{{ end_entity_common.owner_url }}"
    #     referrenc_ca_url: "{{ end_entity_common.referrenc_ca_url }}"
    #     ca:               "staff-issue-ca-01.dum.my"
    #     email_address:    "john.doe@dum.my"