---

- name: Install needed packages
  package:
    name:
    - python3-pyOpenSSL
    - nginx

- name: Start service nginx, if not started
  service:
    name: nginx
    state: started

- name: Stoping service firewalld
  service:
    name: firewalld
    state: stopped
