---

- name:     Create tmp directories
  file:
    path:   "{{ item }}"
    state:  directory
    mode:   0700
  loop:
            - "{{ terraform_base_dir }}"

- name:     Generate terrafom config
  template:
    src:    "terraform_dyn/{{ item }}.tf"
    dest:   "{{ terraform_base_dir }}/{{ item }}.tf"
  loop:
            - main
            - network
            - provider
            - vms