---

- name:           Run terraform init in raw variation
  shell:          "terraform init"
  args:
    chdir:        "{{ terraform_base_dir }}"
  register:       task_result
  ignore_errors:  "{{ debug_output }}"

- debug:
    msg:          "{{ task_result }}"
  when:           debug_output

- name:           Run terraform plan in raw variation
  shell:          "terraform plan"
  args:
    chdir:        "{{ terraform_base_dir }}"
  register:       task_result
  ignore_errors:  "{{ debug_output }}"

- debug:
    msg:          "{{ task_result }}"
  when:           debug_output

- name:           Run terraform apply in raw variation
  shell:          "terraform apply -auto-approve"
  args:
    chdir:        "{{ terraform_base_dir }}"
  register:       task_result
  ignore_errors:  "{{ debug_output }}"

- debug:
    msg:          "{{ task_result }}"
  when:           debug_output
