---

- name:       Generate an root ca private key with the default values
  shell: |
              openssl genrsa \
              -out {{ pki_priv_key }}
  args:
    chdir:    "{{ pki_private_dir }}"
    creates:  "{{ pki_priv_key }}"

###############################################################################

- name:       Check file type of private key
  shell: |
              file {{ pki_priv_key }}
  register:   shell_result
  when:       debug_output

- name:       Output return value
  debug:
    msg:      "{{ shell_result }}"
  when:       debug_output

###############################################################################

- name:       View the content of private key
  shell: |
              openssl rsa \
              -noout \
              -text \
              -in {{ pki_priv_key }}
  register:   shell_result
  when:       debug_output

- name:       Output return value
  debug:
    msg:      "{{ shell_result }}"
  when:       debug_output
