---

- name: Disable SELinux
  selinux:
    state: disabled

- name: Install needed packages
  package:
    name:
    - python3-pyOpenSSL
    - nginx

- name: Start service nginx, if not started
  service:
    name:    nginx
    state:   started

- name: Stoping service firewalld
  service:
    name:    firewalld
    state:   stopped

# - name: Create a base directory for policy ca
#   file:
#     path:    "{{ pki_workspace }}"
#     state:   directory
#     mode:    '0700'

- name: Create public directories for ca
  file:
    path:    "{{ item }}"
    state:   directory
    mode:    'u=rwx,g=rx,o=rx'
  loop:
    - "{{ pki_csr_local_dir }}"
    - "{{ pki_workspace }}"

- name: Create private directories for ca
  file:
    path:    "{{ item }}"
    state:   directory
    mode:    'u=rwx,g=rx,o-rwx'
  loop:
    - "{{ pki_ca_dir }}"
    - "{{ pki_end_entities_dir }}"

- name: Include nginx setup for fedora
  include: "fedora_nginx.yml"